"""empty message

Revision ID: 29ed9b17ebf9
Revises: 4ee2f6d9d214
Create Date: 2014-11-11 10:35:41.505728

"""

# revision identifiers, used by Alembic.
revision = '29ed9b17ebf9'
down_revision = '4ee2f6d9d214'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
